os:
- linux
- osx
language: node_js
node_js:
- '10'
addons:
  firefox: latest
  chrome: stable
cache:
  directories:
  - "./node_modules"
install:
- npm install
script:
- npm run test -- carousel --watch false
before_deploy:
- npm run build
- cd dist/carousel
deploy:
  provider: npm
  email: gabriel20053@gmail.com
  skip_cleanup: true
  api_key:
    secure: rYFvJEh5vaxPhr1vpLnxEPPXFTEvPiYAmDd8PSVL7y8qgOh+oxpHGoY0ZCJvzdDzL14K8hBL807C5sALvr9WzVexgQWA51qOEYnmQh3C/znedryoQsnOe/3JsleOLg8OgXofmnC++ZKSwGmbTzfRexR1OGEcpcZ3OZ1SzMpmUkd+CxG6GCbciWHY36N/fdNzOmmFJMKaKf8EsNk+OeLvtkn+5J/qozwCGfAh3HUkjenmfgMJpMk8igx7lDX1/JaBK9jN9zRab5IbD+OT7Gg8llAJZLucZtbVG6nI9PFhjflGRGpj3y3SGyv/jYcd0FryeIOs4ax9N5Qlq3HWZy9z5tbRxWZuLMgc9B9o9f3xX985lAWngwyElOp+H01/HEc0cTz8xxAdVuGpCcaI1tLYdN4BhYHlskLBhCzgG3N3JIrPiap30VCdZnWIW/0NWxXforazeigtrp1yrBgSHrccFfRU+p8KwvLNCzglpYP7PfusxCQMr4tOzPJL+Ao47UUZAUEI76Xc8ALEC8ljNXsNkbQUW3KkJSB0WxbTIZhfgTLajiEyW3URLS4CtZuNxLXTXHS4Fc8pKVMDUkHCz/snbAIKBiq/0KarzWvax71J5uuNBw3QegjPhotaLflELK7omHQ+6n9RPwCRjr3ct9mDky0sys4Cy13NZ9cROrSq7lA=
  on:
    tags: true
    repo: gabrielbusarello/material2-carousel
